### ISSUE TITLE
Support for private repositories

### ISSUE THREAD

**Issue by tenshiAMD** [kbrashears5/github-action-repo-settings-sync#3]
Greetings @kbrashears5,  I find this workflow very useful in our use cases. May I know if can we include private repositories too? Let us know. Thank you.

**Comment by ghost** [comment]
#### AUTOMATICALLY GENERATED by kbrashears5/github-action-issue-notifier

Mentioning @kbrashears5 to notify them. This will be looked at soon!

**Comment by kbrashears5** [comment]
Does it not work? I think it should

**Comment by tenshiAMD** [comment]
@kbrashears5 I mean if we could set the workflow to include both public and private repositories without specifying individually, is that possible now?

**Comment by kbrashears5** [comment]
looking into this, not sure it's possible with how it's currently setup.

Using [this](https://docs.github.com/en/rest/repos/repos#list-repositories-for-a-user) endpoint on the API and it explicitly says public repositories

**Comment by tenshiAMD** [comment]
@kbrashears5 I think need we can use [this](https://docs.github.com/en/rest/repos/repos#list-repositories-for-the-authenticated-user) instead to include repositories regardless of whether it is public or private. What do you think? Let me know. Thank you.
