### ISSUE TITLE
Implement iteration with pagination of repositories if over 100

### ISSUE THREAD

**Issue by tenshiAMD** [kbrashears5/github-action-repo-settings-sync#6]
Due to the max limit of records per page of 100 (https://github.com/kbrashears5/github-action-repo-settings-sync/pull/5), we need to implement iteration with pagination to support 100+ repositories (public and private).

**Comment by ghost** [comment]
#### AUTOMATICALLY GENERATED by kbrashears5/github-action-issue-notifier

Mentioning @kbrashears5 to notify them. This will be looked at soon!
