### ISSUE TITLE
Implement remove all or individually unselect settings for branch protection

### ISSUE THREAD

**Issue by tenshiAMD** [kbrashears5/github-action-repo-settings-sync#7]
I suggest that we have more control over the settings for branch protection, I suggest having options like `BRANCH_PROTECTION: true (default: false - if false will remove the branch protection)` and for other options, if the setting will have `null` as a value it should somehow unselect the specific settings regarding branch protection. @kbrashears5 what do you think? please let us know. Thank you.

**Comment by ghost** [comment]
#### AUTOMATICALLY GENERATED by kbrashears5/github-action-issue-notifier

Mentioning @kbrashears5 to notify them. This will be looked at soon!
